name: Report a security vulnerability
description: Flag a potential security issue in Snap to AI
labels: [security]
body:
  - type: markdown
    attributes:
      value: |
        If your report contains confidential information, please submit it via [Security disclosures](https://msrc.microsoft.com/create-report) instead.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the vulnerability
      placeholder: e.g. Privilege escalation when using XYZ
    validations:
      required: true
  - type: textarea
    id: affected_versions
    attributes:
      label: Affected versions / environments
      description: Include app version, Windows build, and any configuration prerequisites
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Outline the vulnerability, including components and any observed error messages
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: List clear steps. If the issue is theoretical, describe the scenario and assumptions.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact assessment
      description: What is the potential impact if the vulnerability is exploited?
    validations:
      required: true
  - type: textarea
    id: mitigation
    attributes:
      label: Temporary mitigations
      description: Optional suggestions to reduce risk until a fix ships
